"""Validate public synthetic PREDAP workflow outputs.

This validator is intentionally platform-local. It checks the files generated by
``examples/synthetic/predap_synthetic_workflow.py`` without importing the
separate inference repository.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


REQUIRED_PREDICTION_COLUMNS = {
    "code",
    "target_date",
    "init_forecast_date",
    "final_forecast_date",
    "prediction_origin_date",
    "horizon_day",
    "forecast",
    "lookback",
    "model_id",
    "model_stage_reached",
    "selected_model_type",
    "model_selection_reason",
    "selected_stage_wape",
    "univariate_wape",
    "diagnostics_wape",
    "seasonal_wape",
    "predictions",
    "ci_lower",
    "ci_upper",
    "velocity",
    "acceleration",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate synthetic PREDAP workflow outputs.")
    parser.add_argument("--output-dir", default="runtime/synthetic_demo")
    return parser.parse_args()


def read_json(path: Path) -> object:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    return json.loads(path.read_text(encoding="utf-8-sig"))


def validate_output_dir(output_dir: Path) -> dict[str, object]:
    retrieval_dir = output_dir / "retrieval_export"
    model_dir = output_dir / "model_bundle"
    inference_dir = output_dir / "inference"

    history_path = retrieval_dir / "historical_daily.csv"
    codes_path = retrieval_dir / "target_codes_models_columns_order.json"
    manifest_path = model_dir / "manifest.json"
    predictions_path = inference_dir / "predictions.csv"
    wide_predictions_path = inference_dir / "predictions_wide.csv"
    metrics_path = output_dir / "metrics.json"

    for path in [history_path, codes_path, manifest_path, predictions_path, wide_predictions_path, metrics_path]:
        if not path.exists():
            raise FileNotFoundError(f"Missing synthetic output: {path}")

    codes = read_json(codes_path)
    if not isinstance(codes, list) or not codes or not all(isinstance(code, str) and code for code in codes):
        raise ValueError(f"{codes_path} must be a non-empty JSON list of target-code strings.")

    with history_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        history_columns = set(reader.fieldnames or [])
        missing_history_columns = {"timestamp", *codes} - history_columns
        if missing_history_columns:
            raise ValueError(f"{history_path} is missing columns: {sorted(missing_history_columns)}")
        history_rows = sum(1 for _ in reader)
        if history_rows == 0:
            raise ValueError(f"{history_path} has no data rows.")

    manifest = read_json(manifest_path)
    if not isinstance(manifest, dict):
        raise ValueError(f"{manifest_path} must contain a JSON object.")
    if manifest.get("contains_real_data") is not False:
        raise ValueError(f"{manifest_path} must declare contains_real_data=false.")
    if manifest.get("target_codes") != codes:
        raise ValueError(f"{manifest_path} target_codes must match {codes_path}.")

    model_counts: dict[str, int] = {}
    for code in codes:
        code_model_dir = model_dir / "models" / code
        model_files = sorted(code_model_dir.glob("*.json"))
        if not model_files:
            raise ValueError(f"No dummy model files found for code {code}: {code_model_dir}")
        model_counts[code] = len(model_files)

    with predictions_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        prediction_columns = set(reader.fieldnames or [])
        missing_prediction_columns = REQUIRED_PREDICTION_COLUMNS - prediction_columns
        if missing_prediction_columns:
            raise ValueError(f"{predictions_path} is missing columns: {sorted(missing_prediction_columns)}")
        prediction_rows = sum(1 for _ in reader)
        if prediction_rows == 0:
            raise ValueError(f"{predictions_path} has no data rows.")

    with wide_predictions_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        wide_columns = set(reader.fieldnames or [])
        missing_wide_columns = {"prediction_origin_date", "timestamp", *codes} - wide_columns
        if missing_wide_columns:
            raise ValueError(f"{wide_predictions_path} is missing columns: {sorted(missing_wide_columns)}")
        for code in codes:
            for suffix in [
                "ci_lower",
                "ci_upper",
                "forecast",
                "lookback",
                "horizon_day",
                "model_id",
                "model_stage_reached",
                "selected_model_type",
                "selected_stage_wape",
            ]:
                column = f"{code}__{suffix}"
                if column not in wide_columns:
                    raise ValueError(f"{wide_predictions_path} is missing column: {column}")
        wide_prediction_rows = sum(1 for _ in reader)
        if wide_prediction_rows == 0:
            raise ValueError(f"{wide_predictions_path} has no data rows.")

    metrics = read_json(metrics_path)
    if not isinstance(metrics, dict) or metrics.get("contains_real_data") is not False:
        raise ValueError(f"{metrics_path} must declare contains_real_data=false.")

    return {
        "output_dir": str(output_dir),
        "target_codes": codes,
        "history_rows": history_rows,
        "prediction_rows": prediction_rows,
        "wide_prediction_rows": wide_prediction_rows,
        "model_counts": model_counts,
    }


def main() -> int:
    args = parse_args()
    summary = validate_output_dir(Path(args.output_dir))
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
